In [1]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
# grad来存储梯度
# 一个标量函数关于向量x的梯度是向量，并且与x具有相同的形状

x.requires_grad_(True)  # 等价于x=torch.arange(4.0,requires_grad=True)
x.grad  # 默认值是None

In [3]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
# 调用反向传播函数来自动计算y关于x每个分量的梯度，并打印这些梯度

y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
# 函数y的梯度为4x

x.grad == 4 * x

tensor([True, True, True, True])

In [6]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值

x.grad.zero_()
y = x.sum()
y

tensor(6., grad_fn=<SumBackward0>)

In [7]:
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [8]:
# 对非标量调用backward需要传入一个gradient参数，该参数指定微分函数关于self的梯度。
# 本例只想求偏导数的和，所以传递一个1的梯度是合适的
x.grad.zero_()
y = x * x

# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [9]:
# 分离计算

x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [10]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])