In [12]:
import torch

x = torch.arange(12)
x
x.shape
x.numel()

X = x.reshape(3,4)
X
torch.zeros(2, 3, 4)
torch.ones(2, 3, 4)
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4]])

In [14]:
X = torch.arange(12).reshape(3, 4)
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])

In [15]:
torch.cat((X, Y), dim=1)

tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])

In [16]:
X.sum()

tensor(66)

In [19]:
# 广播机制
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [20]:
X[1, 2] = 9
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

In [21]:
# 区域赋值
# 第一行和第一行全部赋值为12
X[0:2, :] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

In [22]:
#运行操作后变量被分配了新内存
before = id(Y)
Y = Y + X
id(Y) == before

False

In [23]:
# 执行原地操作
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2913229027344
id(Z): 2913229027344


In [24]:
# 执行原地操作
before = id(X)
X += Y
id(X) == before

True

In [25]:
#转化为Numpy张量
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [27]:
#将大小为1的张量转换为Python标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)